name: Release to Azure

on:
  push:
    branches: [ princess ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.401
    - name: Install dependencies
      run: dotnet restore
    - name: Install libman and signalr
      run: |
        cd Server
        dotnet tool restore
        dotnet libman restore
        # fail if libman couldn't download the files.
        if [[ -f wwwroot/js/dist/browser/signalr.js && -f wwwroot/js/dist/browser/signalr.min.js ]]; then
          exit 0;
        else
          exit 1;
        fi
    - name: Update build info
      run: |
        cd Server
        sed -i "s/@@GIT_HASH@@/$GITHUB_SHA/" BuildInfo.cs 
        sed -i "s/@@BUILD_TIME@@/$(date +%s)/" BuildInfo.cs 
    - name: Publish
      run: dotnet publish --configuration Release --no-restore -o built
    - name: Ahead-of-time compress static assets
      run: |
        cd built
        gzip -k --best wwwroot/js/*.js
        gzip -k --best wwwroot/js/*.js.map
        gzip -k --best wwwroot/js/dist/browser/*.js
        gzip -k --best wwwroot/js/dist/browser/*.js.map
        gzip -k --best wwwroot/css/*.css
        gzip -k --best wwwroot/*.xml
        gzip -k --best wwwroot/*.webmanifest
        gzip -k --best wwwroot/*.svg
        gzip -k --best wwwroot/*.html
        brotli -k --best wwwroot/js/*.js
        brotli -k --best wwwroot/js/*.js.map
        brotli -k --best wwwroot/js/dist/browser/*.js
        brotli -k --best wwwroot/js/dist/browser/*.js.map
        brotli -k --best wwwroot/css/*.css
        brotli -k --best wwwroot/*.xml
        brotli -k --best wwwroot/*.webmanifest
        brotli -k --best wwwroot/*.svg
        brotli -k --best wwwroot/*.html
    - name: Azure Login
      uses: Azure/login@v1
      with:
        # Paste output of `az ad sp create-for-rbac` as value of secret variable: AZURE_CREDENTIALS
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: Azure WebApp
      uses: Azure/webapps-deploy@v2
      with:
        # Name of the Azure Web App
        app-name: BuzzOffDev
        # Applies to Web App only: Path to package or folder. *.zip, *.war, *.jar or a folder to deploy
        package: built
        # Enter the start up command. For ex. dotnet run or dotnet run
        startup-command: dotnet BuzzOff.Server.dll

